# Generated by Django 5.1.4 on 2024-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Адрес')),
                ('browser_info', models.TextField(verbose_name='Информация о браузере')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время клика')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='Проект')),
            ],
        ),
    ]
