# Generated by Django 5.1.4 on 2024-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_click_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='project',
            field=models.SlugField(default='default', verbose_name='Проект'),
        ),
    ]
